### ISSUE TITLE
SRV Connection Format

### ISSUE THREAD

**Issue by kiosion** [massivefermion/gleam_mongo#1]
Thanks for your work on this library & `gleam_bson`! Do you have any plans to add support for MongoDB's SRV connection string format? I'm still fairly new to Gleam but would be happy to work on a PR to add support if you don't.

**Comment by massivefermion** [comment]
The SRV format is used to signal to the client that it needs to do a DNS lookup and get a list of connection strings to connect to and so is useful when you're trying to connect to a mongodb cluster. But since this package does not support mongodb clusters yet, adding support for the SRV connection format is pointless.
Of course supporting mongodb clusters is part of the plan but It's going to be a long-term goal!

**Comment by kiosion** [comment]
Gotcha, I totally missed that in the readme 😅
